### ISSUE TITLE
Including via NPM complains that its pre-built

### ISSUE THREAD

**Issue by marr** [jessepollak/payment#1]
Hi, 
I am including the payment module in a node application, and building with webpack. I see the following warning when building:

WARNING in ./~/payment/lib/payment.js
Critical dependencies:
1:459-466 This seem to be a pre-built javascript file. Even while this is possible, it's not recommended. Try to require to orginal source to get better results.
 @ ./~/payment/lib/payment.js 1:459-466

**Comment by mitchellvanw** [comment]
@jessepollak I just started using `payment` and getting the exact same warning.
My import statement `import Payment from 'payment/lib/payment'`
