### ISSUE TITLE
Diners club cards format as Visa

### ISSUE THREAD

**Issue by chrissrogers** [jessepollak/payment#100]
We've had a report of incorrect formatting on Diner's Club test cards: recurly/recurly-js#476

The correct formatting would be `3056 930902 5904` (test card number) but the lib currently formats that as ` 3056 9309 0259 04`.

**Comment by melloware** [comment]
@chrissrogers Please feel free to provide a PR if you have a fix.

**Comment by chrissrogers** [comment]
This can be closed. I just gave that test number a run and it formats properly. I haven't dug into whether my report was initially invalid or whether the issue had resolved in the interim.. but either way it's behaving as expected now!

**Comment by melloware** [comment]
Cool most likely it was resolved since you initially reported. Thanks!
