### ISSUE TITLE
Troy Credit Card Support

### ISSUE THREAD

**Issue by medetcan** [jessepollak/payment#103]
Hi, can you add support for Troy credit cards ?

Troy credit card patterns : /^(?:9792|65\d{2}|36|2205)\d{12}$ /

**Comment by uslualper** [comment]
Troy card is still not added. Does anyone else work on this?

**Comment by melloware** [comment]
Please try Payment 2.4.0 or Card 2.5.0 if using that.  Troy should be there.

**Comment by melloware** [comment]
@jessepollak If you give me access to the Payment repo I can clean all these up too.

**Comment by jessepollak** [comment]
Done

**Comment by melloware** [comment]
This was released in 2.4.0
