### ISSUE TITLE
JCB regex wrong

### ISSUE THREAD

**Issue by thuonghoangdanh** [jessepollak/payment#121]
I test card number: 3518914107195001
Returned: `card_type: null`

**Comment by melloware** [comment]
I can confirm this is not registering as a JCB card.  Let me look into this

**Comment by melloware** [comment]
You can grab the latest one from the /dist folder here: https://github.com/jessepollak/payment/tree/master/dist

Its fixed and thanks for reporting!

**Comment by thuonghoangdanh** [comment]
OK. Thanks
