### ISSUE TITLE
Does not build under webpack

### ISSUE THREAD

**Issue by pospi** [jessepollak/payment#15]
Modules which `require(payment)` as a dependency cause production webpack builds to fail. It seems like the fact that all files are bundled together is an issue; suspect the fix is to setup a build process that compiles each coffeescript file into a *separate* javascript file, rather than bundling them all together.

The error webpack outputs is:
```
WARNING in ./~/card-react/~/payment/lib/payment.js
Critical dependencies:
1:459-466 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/card-react/~/payment/lib/payment.js 1:459-466
```

Though it presents as a warning and will pass in some development configurations, it *will* fail in a production build command.

**Comment by pospi** [comment]
Sorry, just realised this is a duplicate of #1. However the fix specified there (loading `payment/src/payment` instead of just `payment`) doesn't work - you end up with the same error from a dependency of payment itself:

```
WARNING in ./~/card-react/~/payment/~/qj/lib/qj.js
Critical dependencies:
1:449-456 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/card-react/~/payment/~/qj/lib/qj.js 1:449-456
```

You would also need to load `qj` by its src path to avoid this. PR incoming..

**Comment by jessepollak** [comment]
This should be fixed under 0.0.10!

**Comment by pospi** [comment]
works great! they are ready to merge over at https://github.com/shatran/card-react/pull/3 once npm updates (:

**Comment by jessepollak** [comment]
whoops! thought I published it - v0.0.10 is now published with the fix!

**Comment by Scottjutsu** [comment]
Is this indeed fixed?  I'm seeing the same warning on 0.0.12 (and webpack 1.12.9)

PS.  Thanks for the great work @jessepollak !

**Comment by FutureKode** [comment]
+1 seeing the same issue in webpack

**Comment by chrisfinch** [comment]
Seeing the same issue here aswell.

**Comment by chrisfinch** [comment]
@Scottjutsu @FutureKode did you find another library to work with instead of this one?

@jessepollak would it be possible to re-open this issues again?

**Comment by jessepollak** [comment]
Reopened — I can take a look at this over the weekend!

**Comment by chrisfinch** [comment]
@jessepollak thanks dude 👍

**Comment by jessepollak** [comment]
Hi, I've been investigating this and it's related to the fact that we build with browserify (see issue [here](https://github.com/webpack/webpack/issues/1617)). I'm going to switch the builds of this, [qj](https://github.com/jessepollak/qj) and [card](https://github.com/jessepollak/card) to webpack to resolve, hopefully in the next week.

**Comment by jessepollak** [comment]
Hi — can y'all try building with `2.0.0-beta1`? I believe all these issues are now resolved :)
