### ISSUE TITLE
The length of the visa card is 13, 16, please update

### ISSUE THREAD

**Issue by thuonghdbhsoft** [jessepollak/payment#150]
Here is the link I refer to it
https://en.wikipedia.org/wiki/Payment_card_number

**Comment by melloware** [comment]
Actually see this: https://github.com/jessepollak/payment/issues/24

**Comment by melloware** [comment]
Actually its been updated to only 13, 16.  I am going to fix it to 16.

**Comment by sgtcoder** [comment]
I am using the latest card.js from cdnjs. 2.5.3. And it still allows for 19 digits.

**Comment by melloware** [comment]
yep Card has not been updated yet to Payment 2.4.4

**Comment by sgtcoder** [comment]
I see, I didn't know they were related.

It would be nice to just have an option to choose which cards are supported. Otherwise great plugin!
