### ISSUE TITLE
format credit card number after Autofill 

### ISSUE THREAD

**Issue by jack-guide** [jessepollak/payment#155]
Hi,

is there a way to format the credit card number after Autofill by the browser.

e.g. the user has their card details saved in chrome / Edge etc and is prompted to use it when they enter the credit card field. the Autofil enters the card number without spaces e.g. 4444333322221111 and it is not automatically formatted to 4444 3333 2222 1111.

if you paste 4444333322221111 into the credit card box it does format it 4444 3333 2222 1111.

thanks for your help.

very useful library

jack

**Comment by melloware** [comment]
Hmmmm i would assume autofill would fire the change event.  If you do some research on what event is fired on autofill we might be able to fix it.

**Comment by jack-guide** [comment]
the following fires:

$("[id*='CCInputFieldName']").on('blur input', function () {
alert();
});

but i do not think i have access to a function to format the input box

thanks for replying

**Comment by melloware** [comment]
Weird these are the DOM events mapped to the field...  Looks like formatCardNumber is called on "input" but not on "blur" but i thought "input" should cover it?

```
  @formatCardNumber: (el, maxLength) ->
    Payment.restrictNumeric el
    QJ.on el, 'keypress', restrictCardNumber(maxLength)
    QJ.on el, 'keypress', formatCardNumber(maxLength)
    QJ.on el, 'keydown', formatBackCardNumber
    QJ.on el, 'keyup blur', setCardType
    QJ.on el, 'paste', reFormatCardNumber
    QJ.on el, 'input', formatCardNumber(maxLength)
```

**Comment by jack-guide** [comment]
![CC Autofil](https://user-images.githubusercontent.com/7604335/121376799-1b6bb480-c942-11eb-99a9-313759f2330f.JPG)

that is a bit beyond my technical knowledge.

at the moment autofill is unformatted like this

**Comment by jack-guide** [comment]
![CC Manual Entry](https://user-images.githubusercontent.com/7604335/121377032-52da6100-c942-11eb-9b4c-87c6fcb103d8.JPG)

when i manually key them in, its formatted correctly.

the same is true if i paste 4444333322221111

**Comment by melloware** [comment]
Can you try something. Can you edit your payment.js locally and try it. I already had the `input` event so I added a `blur` event to reformatCardNumber.  Which is similar to the 2 Jquery events you have above.

```javascript
Payment.formatCardNumber = function(el, maxLength) {
    Payment.restrictNumeric(el);
    QJ.on(el, 'keypress', restrictCardNumber(maxLength));
    QJ.on(el, 'keypress', formatCardNumber(maxLength));
    QJ.on(el, 'keydown', formatBackCardNumber);
    QJ.on(el, 'keyup blur', setCardType);
    QJ.on(el, 'blur', reFormatCardNumber);
    QJ.on(el, 'paste', reFormatCardNumber);
    QJ.on(el, 'input', formatCardNumber(maxLength));
    return el;
  };
```

I added the line

```javscript
    QJ.on(el, 'blur', reFormatCardNumber);
```

**Comment by jack-guide** [comment]
perfect! that worked

genius

**Comment by melloware** [comment]
Thanks for testing fixed for 2.4.4

**Comment by jack-guide** [comment]
rockstar

**Comment by melloware** [comment]
I have to revert this change as it broke mobile browsers see #161

**Comment by osrl** [comment]
I still have this issue on 2.4.6

**Comment by melloware** [comment]
Yes see my comment above that is had to be reverted because it broke mobile browsers
