### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [jessepollak/payment#171]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by jessepollak** [comment]
Hi - feel free to shoot me an email at the email on my profile, thanks!

**Comment by melloware** [comment]
@jessepollak Can you also disable the need to PR's to pass the build check?  All of our PR's are blocked right now because of this..

**Comment by melloware** [comment]
@JamieSlome was this resolved?

**Comment by JamieSlome** [comment]
It has not been resolved yet, as far as we are aware.

@jessepollak - we sent an e-mail quite a while ago, but you can find the report directly here:

https://huntr.dev/bounties/46c74b89-6722-48f4-b4a3-19b2741fd1dc/

It is private and only accessible to you. Let me know if you have any questions 👍

**Comment by melloware** [comment]
@JamieSlome can you add me to be able to see it.  @jessepollak allowed me to publish this module on NPM even though he did not make me an owner of this repo. I would like to get this issue fixed and pushed to NPM if possible

**Comment by JamieSlome** [comment]
@melloware - I have added you as a maintainer for this repository 👍 

If you view the report again, you should be able to see its contents. Let me know if you are having any issues.
