### ISSUE TITLE
"Error: Cannot find module 'coffeeify' from 'card-react/node_modules/payment'"

### ISSUE THREAD

**Issue by shatran** [jessepollak/payment#18]
Hi @jessepollak,
After I've updated card-react to get payment v0.0.10, I get this error when i try to build it:
"Error: Cannot find module 'coffeeify' from 'card-react/node_modules/payment'"
and i've noticed you added coffeeify browserify transform to package.json.
So i think 'coffeeify should be added to 'dependencies' section in package.json.
I've added it in card-react's package.json and it works but i think it should be in 'payment'.

**Comment by jessepollak** [comment]
Just fixed this — will release in v0.1.0!

**Comment by shatran** [comment]
Thanks!
