### ISSUE TITLE
Visa 4000000000000000030 doesn't pass the validation

### ISSUE THREAD

**Issue by joaojeronimo** [jessepollak/payment#24]
```assert(Payment.fns.validateCardNumber('4000000000000000030'), 'visa')``` throws.

**Comment by jessepollak** [comment]
So, according to [this article](http://validcreditcardnumbers.info/?p=9), Visa card numbers can only be 13 or 16 digits long. This card number is 19 digits long. Are you sure this is supposed to be a valid Visa card number?

I'm closing, please reopen if you think it is!

**Comment by joaojeronimo** [comment]
According to the [Bank card number wikipedia page](https://en.wikipedia.org/wiki/Bank_card_number) VISA card numbers can have 13, 16 and 19 digits. I forgot where I got the number from (will get the source on Monday) but that is a visa 19 digit test card number and it goes through cybersource at least.

**Comment by jessepollak** [comment]
Awesome, thank you for that link — I'll update to validate 19 character numbers!
