### ISSUE TITLE
Update the pattern of ELO.

### ISSUE THREAD

**Issue by cauealves** [jessepollak/payment#27]
This is the updated table of bins at `elo`:

![bins 1](https://cloud.githubusercontent.com/assets/7065285/14727592/e83d342c-0802-11e6-88d9-fb3d3eec2301.png)
 
When I test with the `457393` was a problem, see: 

![captura de tela 2016-04-21 as 20 53 58](https://cloud.githubusercontent.com/assets/7065285/14727613/366dfe9c-0803-11e6-94a4-20a50354bda5.png)

**Comment by mateuspadua** [comment]
@ceasbz tudo bem? Estou precisando de uma tabela oficial de bins da ELO, aonde vc encontrou essa? Se puder me passar, me ajudará muito, Obrigado.
