### ISSUE TITLE
Support MasterCard series 2 bins

### ISSUE THREAD

**Issue by joaojeronimo** [jessepollak/payment#33]
Mastercard is introducing a new range of card numbers with IINs ranging from 22210000 to 27209999, effective on October 14th.

Relevant links: [[1](https://www.forte.net/blog/mastercard-bin-range-coming/)], [[2](https://en.wikipedia.org/wiki/Bank_card_number)]

**Comment by jessepollak** [comment]
Do you have any example cards that we can test on for this?

**Comment by bedeMarkRadford** [comment]
So far there's been no test card number issued.
I've been offered this regex:
(5[1-5]\d{4}|677189)\d{10}$|^(222[1-9]|2[3-6]\d{2}|27[0-1]\d|2720)\d{12}$
