### ISSUE TITLE
Expose formatCardCVC and formatCardExpiry under Payment.fns

### ISSUE THREAD

**Issue by chrisfinch** [jessepollak/payment#35]
Hi - great library, thanks for your work on it.

I'm trying to integrate this library with a React.js payment form. This stops me from using and direct event handlers on the input fields.

I've had success with using the `Payment.fns.formatCardNumber` function to help me format my user input as part of the react data flow but unfortunately the related functions for expiry and cvc are not exposed in their non-event-handler form as the card number function is.

Would it be possible to expose these so I can use them as stand alone string formatters?

Thanks!

**Comment by danieljuhl** [comment]
@chrisfinch are you still looking for a solution? I have integrated Payment and Card with React (as standalone) and thus, have extracted the methods mentioned. Currently in a private repo, but if you're interested, I can make a public module.

**Comment by jessepollak** [comment]
hey @danieljuhl I'd also be happy to accept a PR if you'd like to submit one. Thanks!

**Comment by pudgereyem** [comment]
@danieljuhl I'd like that too. Thanks!

**Comment by danieljuhl** [comment]
I'm working on a payment integration right now, but can't say if it's a week or two, until I can have a PR ready.

But it will come 😄

**Comment by pudgereyem** [comment]
@danieljuhl okay, thanks! :)
