### ISSUE TITLE
keypress event is ignored on android (mobile)

### ISSUE THREAD

**Issue by vikmovcan** [jessepollak/payment#36]
On android devices keypress events are not being triggered.
Input is not being validated/formatted as a result. it works fine on desktop and iOS. 

I used two android(v6 and v4.4) devices to test this using chrome/stock browser.

can be reproduced here: http://jessepollak.github.io/payment/example/

Example above demonstrates that card number is not being validated because 
https://github.com/jessepollak/payment/blob/master/lib/payment.js#L787 is not being triggered

**Comment by joshwcomeau** [comment]
I'm having the same issue. Has a fix been discovered yet?

**Comment by ahumphreys87** [comment]
@jessepollak any ideas on this?

**Comment by joshwcomeau** [comment]
The issue is that the code uses the `keypress` event, which is not supported by Android. 

I tried switching it to `keydown`, but I ran into some other issues, so in the end I just opted to leave Android inputs unformatted/validated, and to pass it along to Stripe.

**Comment by Swivelgames** [comment]
I've forked the repo in an attempt to remedy it myself; We just went to production unaware of this defect, until sales started dropping.

If I get a chance to I'll post up a pull request if I figure out a good solution. Don't let that stop you from looking into it whenever you have time @jessepollak -- It would be much appreciated!

**Comment by egoldblum** [comment]
Also ran into this bug.  `jquery.payment`, from which this library was derived(?), handles this using `input` event and reformatting.  See: https://github.com/stripe/jquery.payment/commit/273d79a08c82795eb24ec36463055e973abfe43c

**Comment by evanjmg** [comment]
Any hotfixes/quick fixes for this? Using Samsung S7 edge for any browser. The correct spacing on the input works for Payment.formatCardNumber(document.querySelector('input.card-number'));
It works for everything else on Desktop and iPhone - I've tried - IE, Firefox, Safari, Opera. <input type="text" id="payment-1" class="card-number form-control" id="card-number" placeholder="Card Number">

**Comment by dane-harnett** [comment]
Also experiencing this issue, anyone got any ideas?

**Comment by dane-harnett** [comment]
#63 Hopefully that resolves this

**Comment by JesperWe** [comment]
@dane-harnett That only fixes card number. The other fields have the same issue.

**Comment by lukaVarga** [comment]
@jessepollak any update on this? While the card number works, expiry field doesn't. I'd be willing to make a PR and fix this when I get a chance, but I see that there are several (quite old) open PRs so I'm not sure whether you still accept PRs or decided to move on from the project.

**Comment by yovdesign** [comment]
Hi,
try defining the input as `type="tel"` with  `pattern="\d*"`
works for me... 
hope it helps

**Comment by lukaVarga** [comment]
The expiry field? Nope, doesn't work for me. Tried on android in Chrome just now :/

**Comment by bryantobing12** [comment]
facing the same problem now. did anyone solve this issue?

**Comment by whatevea** [comment]
Guys make sure the form autocomplete is off like this

> <form autocomplete="off" action="/action_page.php">

> <input ....>

**Comment by whatevea** [comment]
> 
> 
> Guys make sure the form autocomplete is off like this
> 
> > <input ....>



> 
> 
> The issue is that the code uses the `keypress` event, which is not supported by Android.
> 
> I tried switching it to `keydown`, but I ran into some other issues, so in the end I just opted to leave Android inputs unformatted/validated, and to pass it along to Stripe.

https://github.com/jessepollak/payment/issues/36#issuecomment-706513924
