### ISSUE TITLE
Payment.fns.formatCardNumber formats maxlength + 1

### ISSUE THREAD

**Issue by janicklas-ralph** [jessepollak/payment#41]
Thank you for this great port.

Payment.fns.formatCardNumber slices on maxlength + 1, this is causing card numbers to accept an extra input.

**Comment by themeteorchef** [comment]
Noticing this, too. Pre-2.0.0 releases don't seem to have the issue (rolled back to 1.0.4 and it disappeared). For clarification, I can type beyond 16 numbers (19) into any field with `formatCardNumber` attached. Thanks in advance for any fixes :)

**Comment by jessepollak** [comment]
Thanks! Fixed in 2.0.3!
