### ISSUE TITLE
When using with React/Redux, it does not fire element's onChange event  every 4 digits when formatting card number

### ISSUE THREAD

**Issue by ferenckv** [jessepollak/payment#53]
If I have an issue with the function formatCreditCard when using React/Redux. It does not fire element's onChange event every 4 digits.

You can see the issue here
http://www.webpackbin.com/Nyy7s1m-f

As you can see, as you fill in the credit card number, the console prints it but it skips the 4th, 8th, 12th digits.

**Comment by gertig** [comment]
@ferenckv I just noticed the same behavior. Were you able to find a workaround?

**Comment by AlexGaspar** [comment]
If we trigger `input` instead of `change` [here](https://github.com/jessepollak/payment/blob/master/src/index.coffee#L173-L183) and allow it to bubble up, it triggers the onChange handler (at least in my case).

```coffee
  QJ.trigger(target, 'change')
```
Into:
```coffee
  target.dispatchEvent new Event('input', bubbles: true)
```

@gertig, @ferenckv: does that work for you?

**Comment by kimmobrunfeldt** [comment]
@AlexGaspar your fix works for me

**Comment by johannesengl** [comment]
What is the progress on the workaround? Will the bug be fixed in the close future or does it make sense to monkey patch it till then.

**Comment by finnp** [comment]
I recommend using this undocumented function:
```js
payment.fns.formatCardNumber(cardNumber)
```

And then bind the following to `onChange`

```js
    this.setState({
      value: payment.fns.formatCardNumber(event.target.value)
    })
```

**Comment by jessepollak** [comment]
We've added more on change events so this should be resolved!

**Comment by bmbrina** [comment]
Hi! I'm having this same issue and I have this in my package.json `"payment": "^2.2.1"`.
