### ISSUE TITLE
Visa cards issue

### ISSUE THREAD

**Issue by cozzbie** [jessepollak/payment#56]
When entering visa cards, input takes more than 16 digits. Mastercard works fine.

**Comment by juliocanares** [comment]
Just to let u know @cozzbie https://blog.vindicia.com/19-digit-visas-and-2-digit-mastercards/ visa is now accepting 19 digits #24

**Comment by juliocanares** [comment]
#24

**Comment by cozzbie** [comment]
@juliocanares :( 

this coding life of ours...we are gonna make it shine...*sobs*...make it shine...make it shine...make it shiiiinnnnnnnneeeee.

Thanks mate

**Comment by simultech** [comment]
@jessepollak 

This is a major issue, as the space that is automatically added to 16 digit VISA cards being formatted intercepts the onChange event, so 16 digit VISA cards never get sent to onChange.

**Comment by TrevorHinesley** [comment]
It works using `Payment.fns.formatCardNumber` so it's definitely the `Payment.formatCardNumber` function malfunctioning

**Comment by cozzbie** [comment]
`Payment.fns.formatCardNumber` doesnt do much formatting though. Not even sure thats part of the api.

**Comment by stanleycyang** [comment]
I am seeing this issue as well. Really buggy as visas are really common

**Comment by cozzbie** [comment]
The 16th character is skipped and replaced by a space and then put back on the entry of the 17th character (18th during formatting). It might be best to use another library and combine some algo to help. Thats what I did.

**Comment by gmoreira** [comment]
@cozzbie have a look at the pull request just submitted 👍

**Comment by cozzbie** [comment]
Awesome @gmoreira lets wait for the it to merged then we can update. Currently combining two libraries to get this to work and its working fine...for a hack. 👍

**Comment by jessepollak** [comment]
This just got merged and will be shipped in 2.2.5!

**Comment by jessepollak** [comment]
2.2.0*

**Comment by cozzbie** [comment]
AWESOME!!!!
