### ISSUE TITLE
formatCardNumber breaks paste in Safari

### ISSUE THREAD

**Issue by seawolff** [jessepollak/payment#57]
Using `2.1.4`

**Comment by seawolff** [comment]
Using `2.1.4`

**Comment by emiloberg** [comment]
@seawolff I'm seeing the same thing, did you do any more exploration around this? E.g. if it worked with the previous version or something like it?

**Comment by dpauley** [comment]
We're running into this issue, too. Any updates?

**Comment by melloware** [comment]
Seems to be working fine now in Safari with version 2.4.3
