### ISSUE TITLE
formatCardNumber is duplicating input

### ISSUE THREAD

**Issue by ccheney** [jessepollak/payment#59]
http://codepen.io/ccheney/pen/bqErPp

Typing this:
4111111111111111

You end up with this:
411111111111111111

Don't have time to dig into which PR introduced this but I'd recommend sticking with v2.1.4

**Comment by jessepollak** [comment]
Thanks for reporting this - looking into it right now.

**Comment by jessepollak** [comment]
Fixed in 2.2.1!
