### ISSUE TITLE
Some valid cards don't pass the validateCardNumber check

### ISSUE THREAD

**Issue by nnacin** [jessepollak/payment#60]
Although it's a valid credit card, when I enter the card number it doesn't pass the validation.

Do you know what could be the reason?

**Comment by jessepollak** [comment]
Can you give some examples of card numbers that fail validation?

**Comment by nnacin** [comment]
It is an actual card I use so I am not comfortable disclosing it publicly. It's a Maestro credit card, from a European bank.
When I enter it here http://stripe.github.io/jquery.payment/example/ it says the card type is Discover.

**Comment by melloware** [comment]
This was released in 2.4.0 Maestro has been updated
