### ISSUE TITLE
Issue with formatCardNumber - erased characters reappearing on validate

### ISSUE THREAD

**Issue by 0xStarcat** [jessepollak/payment#66]
Using 2.2.1

![screen shot 2017-05-09 at 11 59 22 am](https://cloud.githubusercontent.com/assets/17187192/25861747/97869cf6-34b3-11e7-9e6c-f294dc5f3904.png)

^ It appears like the field is allowing 19 characters + 3 spaces. When a user accidentally goes over 16 characters like in the photo `4242 4242 4242 4242 333` and then goes to erase the extra characters => `4242 4242 4242 4242`, and clicks `Submit` to validate the card, a previously erased extra character appears in the input field => `4242 4242 4242 4242 3` and the card returns invalid.

The input masking is implemented in React, but this probably shouldn't matter.

![screen shot 2017-05-09 at 12 30 54 pm](https://cloud.githubusercontent.com/assets/17187192/25861860/0257c2da-34b4-11e7-9db2-ff5476fdfbcd.png)

**Comment by a-wart** [comment]
+1 have the same issue.
@jessepollak will the fix come?

**Comment by rostislav-mitu** [comment]
+1, the same issue, also in React.

**Comment by jessepollak** [comment]
Will ship this fix in the next version!

**Comment by sengoontoh** [comment]
I'm still seeing this issue where the last erased number shows up on validate.

**Comment by gregkohn** [comment]
Still seeing this issue; the last erased number reappears when typing in next input.
Payment: `2.3.0`
React: `16.8.3`
Gif:
![validation](https://user-images.githubusercontent.com/5114665/57664477-4e59e780-75c6-11e9-8c19-0de53015a0ad.gif)
