### ISSUE TITLE
Issue with multiple forms on the page

### ISSUE THREAD

**Issue by AsWaM** [jessepollak/payment#67]
Hi,

I can't get the form selector to work properly, if I try to select it by ID or by class, I don't get anything, if I let the $('form') selector, it finds its container, adds the image, but can't find the fields (although they are here).

I think this is an issue with the form selector

Card can't find a numberInput in your form.
Card can't find a expiryInput in your form.
Card can't find a cvcInput in your form.
Card can't find a nameInput in your form.

Alex

**Comment by AsWaM** [comment]
My bad. bootstrap is "renaming" my objects. 
<form> --> <div class="form-container active">

**Comment by bradymccain** [comment]
@AsWaM Having the same problem. Can you describe how you fixed it?

**Comment by AsWaM** [comment]
Just name the container and tell it what are its fields
The sample is in MVC but you can do the same in any language
HTML
 <div class="card-wrapper"></div>
            <div id="cardInput">
                <div class="form-group">
                    <div class="col-md-4 col-lg-offset-2">
                        @Html.TextBoxFor(x => Model.NewCard.Number, new { @class = "form-control", placeholder = @Resources.Strings.CARD_NUMBER, @type = "tel" })
                    </div>
                    <div class="col-md-4">
                        @Html.TextBoxFor(x => Model.NewCard.Holder, new { @class = "form-control", placeholder = @Resources.Strings.CARD_OWNER, @type = "text" })
                    </div>
                </div>
 <div class="form-group">
                    <div class="col-md-4 col-lg-offset-2">
                        @Html.TextBoxFor(x => Model.NewCard.Expiration, new { @class = "form-control", placeholder = "MM/YYYY", @type = "tel" })
                    </div>
                    <div class="col-md-4">
                        @Html.TextBoxFor(x => Model.NewCard.Cvc, new { @class = "form-control", placeholder = "CVC", @type = "number" })
                    </div>
                    <div class="col-md-1"> <button class="btn btn-default" type="button" onclick="AddCard()">@Resources.Strings.COMMON_ADD</button></div>
                </div>

Javascript

$('#cardInput').card({
    container: '.card-wrapper',
    formSelectors: {
        numberInput: "input[name='NewCard.Number']",
        expiryInput: "input[name='NewCard.Expiration']",
        cvcInput: "input[name='NewCard.Cvc']",
        nameInput: "input[name='NewCard.Holder']"
    },
    placeholders: {
        number: '**** **** **** ****',
        name: 'Sublime User',
        expiry: '**/****',
        cvc: '***'
    }
});

**Comment by bradymccain** [comment]
The problem is that in the given examples "form" is used - not an id. Once I changed it to the form's id it worked.
