### ISSUE TITLE
The following (valid) credit card number is not accepted

### ISSUE THREAD

**Issue by ohansemmanuel** [jessepollak/payment#74]
For some reason the following credit card number is not accepted:
`5043342567607506`

A quick check on the net shows that the Luhn algorithm accepts this number as a valid credit card number. We also don't have any issues using this card number on our sister website (which uses the JQuery.payment library) so there might be something wrong.

The entire card details:
>Mastercard test card + OTP
Card Number: 5043342567607506
Expiry details: 09/21
CVV: 563
PIN: 1111
OTP: 123456

Below is A GIF of me trying to validate this card number: 

![issue_card_validation](https://user-images.githubusercontent.com/10930234/28143269-9ac4f170-675c-11e7-99b9-dbe1b23b211a.gif)

**Comment by cozzbie** [comment]
Can you verify who the issuer of the credit card is? The library only supports a select of card types and is not just based off Luhn alone. I ran a check on it and I cannot find any issuer attached to it.

**Comment by ohansemmanuel** [comment]
Thanks, @cozzbie . I'm not sure what is wrong any longer. See attached gif, the card number seems to be interpreted as type, *MasterCard* 
![jul-14-2017 18-42-05](https://user-images.githubusercontent.com/10930234/28223771-919c76ea-68c4-11e7-8c8e-b9f090fa8927.gif)

**Comment by ohansemmanuel** [comment]
I do NOT think this has to do with this library. 

Thanks @cozzbie for the time
