### ISSUE TITLE
restrictNumeric blocks pasting with Ctrl+V

### ISSUE THREAD

**Issue by Changaco** [jessepollak/payment#79]
`restrictNumeric()` correctly checks for `e.metaKey || e.ctrlKey`, but these are always `undefined` because `QJ.normalizeEvent()` doesn't copy them from the original event.

Relevant links to the code:

- https://github.com/jessepollak/payment/blob/v2.3.0/dist/payment.js#L372
- https://github.com/jessepollak/payment/blob/v2.3.0/dist/payment.js#L731
- https://github.com/jessepollak/qj/blob/v2.0.0/src/index.coffee#L29

#57 is probably the same issue, since `formatCardNumber()` uses `restrictNumeric()`.

**Comment by jessepollak** [comment]
Thanks for opening this issue — I'd love to accept a PR on qj for this fix. If you can't do it, I can probably take a look this weekend.

**Comment by Changaco** [comment]
@jessepollak I'm not going to work on a fix, sorry. I've decided to consolidate our own module instead of using yours.

**Comment by artemln** [comment]
@jessepollak Please review PR https://github.com/jessepollak/payment/pull/86

**Comment by bobrosoft** [comment]
@jessepollak hi there. Can you review that PR above? Experiencing same issue in our project when using Safari and trying to insert card number with Cmd+V

**Comment by melloware** [comment]
This was released in 2.4.0. If anyting from your PR is not in there please submit another one.
