### ISSUE TITLE
Payment.formatCardNumber is allowing 19 digits

### ISSUE THREAD

**Issue by kgupta1988** [jessepollak/payment#80]
I want to limit the credit card digits to 16, but still it is allowing 19 digits.
**Code:**
`Payment.formatCardNumber(document.querySelector('input.cc-number'), 16);`
What shall I do to restrict it to 16.

**Comment by hoektoe** [comment]
Same issue unless there is card format I am unfamiliar with

**Comment by ziedmahdi** [comment]
duplicat #44
