### ISSUE TITLE
Payment.J is undefined

### ISSUE THREAD

**Issue by kwameopareasiedu** [jessepollak/payment#94]
In your **dist/payment.js**, you forgot the line **Payment.J = QJ**
I managed to fix it by referring to your online demo scripts ...

[Online Demo](http://jessepollak.github.io/payment/example/)

**Comment by Ryuubi** [comment]
Which line did you put Payment.J = QJ?

**Comment by kwameopareasiedu** [comment]
Line 704...
Just before u export it...

**Comment by Ryuubi** [comment]
Yea I found it while looking through the script for the online demo, but thanks for the reply!
