### ISSUE TITLE
On Copy Paste card is not autoformatting.

### ISSUE THREAD

**Issue by karnprem** [jessepollak/payment#99]
When i copy paste card number from stripe. It is not auto formatted and onload of card number also it is not auto formatting. Please check screenshot
![screenshot from 2018-07-25 12-54-48](https://user-images.githubusercontent.com/39363915/43185602-fd13dd4c-9009-11e8-9fd5-4d04a17b52ef.png)

**Comment by melloware** [comment]
This was released in 2.4.0
